// Generated by gencpp from file bumperbot_examples/AddTwoints.msg
// DO NOT EDIT!


#ifndef BUMPERBOT_EXAMPLES_MESSAGE_ADDTWOINTS_H
#define BUMPERBOT_EXAMPLES_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <bumperbot_examples/AddTwointsRequest.h>
#include <bumperbot_examples/AddTwointsResponse.h>


namespace bumperbot_examples
{

struct AddTwoints
{

typedef AddTwointsRequest Request;
typedef AddTwointsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoints
} // namespace bumperbot_examples


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::bumperbot_examples::AddTwoints > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::bumperbot_examples::AddTwoints&) { return value(); }
};

template<>
struct DataType< ::bumperbot_examples::AddTwoints > {
  static const char* value()
  {
    return "bumperbot_examples/AddTwoints";
  }

  static const char* value(const ::bumperbot_examples::AddTwoints&) { return value(); }
};


// service_traits::MD5Sum< ::bumperbot_examples::AddTwointsRequest> should match
// service_traits::MD5Sum< ::bumperbot_examples::AddTwoints >
template<>
struct MD5Sum< ::bumperbot_examples::AddTwointsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::bumperbot_examples::AddTwoints >::value();
  }
  static const char* value(const ::bumperbot_examples::AddTwointsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::bumperbot_examples::AddTwointsRequest> should match
// service_traits::DataType< ::bumperbot_examples::AddTwoints >
template<>
struct DataType< ::bumperbot_examples::AddTwointsRequest>
{
  static const char* value()
  {
    return DataType< ::bumperbot_examples::AddTwoints >::value();
  }
  static const char* value(const ::bumperbot_examples::AddTwointsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::bumperbot_examples::AddTwointsResponse> should match
// service_traits::MD5Sum< ::bumperbot_examples::AddTwoints >
template<>
struct MD5Sum< ::bumperbot_examples::AddTwointsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::bumperbot_examples::AddTwoints >::value();
  }
  static const char* value(const ::bumperbot_examples::AddTwointsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::bumperbot_examples::AddTwointsResponse> should match
// service_traits::DataType< ::bumperbot_examples::AddTwoints >
template<>
struct DataType< ::bumperbot_examples::AddTwointsResponse>
{
  static const char* value()
  {
    return DataType< ::bumperbot_examples::AddTwoints >::value();
  }
  static const char* value(const ::bumperbot_examples::AddTwointsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // BUMPERBOT_EXAMPLES_MESSAGE_ADDTWOINTS_H
