local_costmap:
  global_frame: odom
  robot_base_frame: base_footprint
  static_map: false
  rolling_window: true
  update_frequency: 5.0 #10.0
  publish_frequency: 5.0 #10.0
  resolution: 0.05
  robot_radius: 0.13
  width: 4.0
  height: 4.0
  obstacle_range: 3.0 #3.0
  raytrace_range: 3.5 #3.5
  #origin_x: 0.0
  #origin_y: 0.0
  resolution: 0.05
  transform_tolerance: 1.0
  inflation_radius: 0.1
  cost_scaling_factor: 75 #100.0
  observation_sources: scan
  scan: {sensor_frame: laser_link, data_type: LaserScan, topic: /scan, marking: true, clearing: true}
  
